import React, { useRef } from 'react';
import { 
  Printer, Download, GraduationCap, CheckCircle2, 
  AlertTriangle, Sparkles, TrendingUp, BookOpen, ShieldAlert
} from 'lucide-react';
import { RiskBadge } from '../common/StatCard';

export default function PrintableReportCard({ reportData, onPrint }) {
  const reportRef = useRef(null);

  if (!reportData) return null;

  const { student, performance_summary, subject_marks, weak_areas_identified, ai_recommendations, report_generated_at } = reportData;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* Action Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 rounded-2xl bg-slate-900 border border-slate-800 no-print">
        <div>
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <GraduationCap className="w-5 h-5 text-brand-400" />
            Official Academic Performance Report
          </h2>
          <p className="text-xs text-slate-400">
            Generated by Integrated AI Academic Intelligence Engine • Section 10 Specification
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button 
            onClick={handlePrint} 
            className="btn-primary !py-2 !px-4 text-xs flex items-center gap-2 shadow-glow-brand"
          >
            <Printer className="w-4 h-4" /> Print / Download PDF
          </button>
        </div>
      </div>

      {/* Printable Report Container */}
      <div ref={reportRef} className="printable-card glass-panel p-8 space-y-8 bg-slate-900 text-slate-100 border border-slate-800">
        
        {/* Header / Institutional Branding */}
        <div className="border-b border-slate-800 pb-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-brand-600 flex items-center justify-center text-white font-bold text-xl">
              <GraduationCap className="w-7 h-7" />
            </div>
            <div>
              <h1 className="text-xl font-extrabold text-white tracking-tight uppercase">
                EduVision Institute of Advanced Engineering
              </h1>
              <p className="text-xs text-slate-400">
                Department of Computer Science & Engineering • Academic Session 2025-2026
              </p>
            </div>
          </div>

          <div className="text-left md:text-right text-xs text-slate-400 space-y-0.5">
            <p className="font-semibold text-slate-200">Official Grade Transcript & AI Audit</p>
            <p>Date Generated: {new Date(report_generated_at).toLocaleDateString()}</p>
            <p className="font-mono text-brand-400">Report ID: EDU-2026-REP-{student.id}</p>
          </div>
        </div>

        {/* 1. Student Profile & Summary */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-4 rounded-xl bg-slate-850 border border-slate-800 text-xs">
          <div>
            <span className="text-slate-500 block">Student Name</span>
            <span className="font-bold text-sm text-white">{student.full_name}</span>
          </div>
          <div>
            <span className="text-slate-500 block">Enrollment Number</span>
            <span className="font-bold text-sm text-slate-200 font-mono">{student.enrollment_number}</span>
          </div>
          <div>
            <span className="text-slate-500 block">Semester & Program</span>
            <span className="font-bold text-sm text-slate-200">Semester 6 (B.Tech CSE)</span>
          </div>
          <div>
            <span className="text-slate-500 block">Academic Risk Status</span>
            <div className="mt-0.5">
              <RiskBadge level={performance_summary.risk_level} score={performance_summary.risk_score} />
            </div>
          </div>
        </div>

        {/* 2. Key Performance Metrics Banner */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
            <span className="text-xs text-slate-400 block font-medium">Cumulative Attendance</span>
            <div className="flex items-baseline gap-2 mt-1">
              <span className={`text-2xl font-black ${performance_summary.overall_attendance_pct >= 75 ? 'text-emerald-400' : 'text-rose-400'}`}>
                {performance_summary.overall_attendance_pct}%
              </span>
              <span className="text-[11px] text-slate-400">
                {performance_summary.overall_attendance_pct >= 75 ? 'Meets 75% Requirement' : 'Attendance Deficit Alert'}
              </span>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
            <span className="text-xs text-slate-400 block font-medium">Average Mark Percentage</span>
            <div className="flex items-baseline gap-2 mt-1">
              <span className="text-2xl font-black text-brand-400">
                {performance_summary.average_marks_pct}%
              </span>
              <span className="text-[11px] text-slate-400">Across 4 Enrolled Subjects</span>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
            <span className="text-xs text-slate-400 block font-medium">Academic Trajectory Trend</span>
            <div className="flex items-baseline gap-2 mt-1">
              <span className="text-lg font-bold text-indigo-400 capitalize flex items-center gap-1.5">
                <TrendingUp className="w-4 h-4" /> {performance_summary.trend_status}
              </span>
            </div>
          </div>
        </div>

        {/* 3. Comprehensive Subject Marks Table (25 Internal + 75 External = 100 Final) */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-brand-400" />
              Course Assessment & Mark Breakdown
            </h3>
            <span className="text-xs text-slate-400 font-mono">
              Internal (/25) + Converted External (/75) = Final (/100)
            </span>
          </div>

          <div className="overflow-x-auto rounded-xl border border-slate-800">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-850 text-slate-400 border-b border-slate-800 uppercase font-semibold">
                <tr>
                  <th className="py-3 px-3">Subject Code & Name</th>
                  <th className="py-3 px-2 text-center">Int. Test</th>
                  <th className="py-3 px-2 text-center">Model</th>
                  <th className="py-3 px-2 text-center">Assign</th>
                  <th className="py-3 px-3 text-center bg-brand-950/40 text-brand-300">Internal (/25)</th>
                  <th className="py-3 px-2 text-center">Ext. Raw (/100)</th>
                  <th className="py-3 px-3 text-center bg-indigo-950/40 text-indigo-300">Ext. Conv (/75)</th>
                  <th className="py-3 px-3 text-center bg-slate-800 font-bold text-white">Final (/100)</th>
                  <th className="py-3 px-2 text-center">Grade</th>
                  <th className="py-3 px-2 text-center">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 font-mono">
                {subject_marks.map((m, idx) => (
                  <tr key={idx} className="hover:bg-slate-850/50 transition-colors">
                    <td className="py-3 px-3 font-sans font-medium text-slate-200">
                      <div className="font-bold text-white">{m.subject_code}</div>
                      <div className="text-[11px] text-slate-400">{m.subject_name}</div>
                    </td>
                    <td className="py-3 px-2 text-center">{m.internal_test}</td>
                    <td className="py-3 px-2 text-center">{m.model_exam}</td>
                    <td className="py-3 px-2 text-center">{m.assignments}</td>
                    <td className="py-3 px-3 text-center font-bold text-brand-400 bg-brand-950/20">
                      {m.internal_total_25}
                    </td>
                    <td className="py-3 px-2 text-center">{m.external_raw_100}</td>
                    <td className="py-3 px-3 text-center font-bold text-indigo-400 bg-indigo-950/20">
                      {m.external_converted_75}
                    </td>
                    <td className="py-3 px-3 text-center font-extrabold text-white text-sm bg-slate-800/60">
                      {m.final_mark_100}
                    </td>
                    <td className="py-3 px-2 text-center font-bold text-amber-400">
                      {m.letter_grade}
                    </td>
                    <td className="py-3 px-2 text-center">
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${
                        m.is_passed ? 'bg-emerald-500/20 text-emerald-400' : 'bg-rose-500/20 text-rose-400'
                      }`}>
                        {m.is_passed ? 'Pass' : 'Fail'}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* 4. Weak Areas Identified (Section 10.2) */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-amber-400" />
            Weak Areas & Syllabus Deficit Diagnosis
          </h3>

          {weak_areas_identified && weak_areas_identified.length > 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {weak_areas_identified.map((item, idx) => (
                <div key={idx} className="p-4 rounded-xl bg-amber-950/20 border border-amber-500/30 space-y-2">
                  <div className="flex items-center justify-between">
                    <h4 className="font-bold text-sm text-amber-300">
                      {item.subject_name} ({item.subject_code})
                    </h4>
                    <span className="text-xs font-mono text-amber-400">Final: {item.final_score}/100</span>
                  </div>
                  <ul className="text-xs text-slate-300 space-y-1 list-disc list-inside">
                    {item.reasons.map((r, rIdx) => (
                      <li key={rIdx}>{r}</li>
                    ))}
                  </ul>
                  <div className="pt-2 border-t border-amber-500/20 text-[11px] text-slate-400">
                    <strong className="text-amber-300">Priority Focus Topics: </strong>
                    {item.focus_topics.join(', ')}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="p-4 rounded-xl bg-emerald-950/20 border border-emerald-500/30 flex items-center gap-3 text-emerald-400 text-xs">
              <CheckCircle2 className="w-5 h-5" />
              <span>No critical subject-level weaknesses detected. Consistent mastery across curriculum.</span>
            </div>
          )}
        </div>

        {/* 5. AI Recommendations (Section 10.4) */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-brand-400" />
            AI Academic Intelligence Recommendations
          </h3>

          <div className="space-y-2.5">
            {ai_recommendations.map((rec, idx) => (
              <div key={idx} className="p-3.5 rounded-xl bg-slate-850 border border-slate-800 flex items-start gap-3">
                <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase shrink-0 mt-0.5 ${
                  rec.priority === 'Urgent' ? 'bg-rose-500/20 text-rose-400 border border-rose-500/30' :
                  rec.priority === 'High' ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30' :
                  'bg-brand-500/20 text-brand-400 border border-brand-500/30'
                }`}>
                  {rec.priority}
                </span>
                <div>
                  <h5 className="text-xs font-bold text-slate-200">{rec.category}</h5>
                  <p className="text-xs text-slate-400 mt-0.5">{rec.action}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Signatures & Certification */}
        <div className="pt-8 border-t border-slate-800 grid grid-cols-2 md:grid-cols-3 gap-8 text-center text-xs text-slate-400">
          <div>
            <div className="h-12 border-b border-slate-700 mx-auto w-36"></div>
            <p className="mt-2 font-medium text-slate-300">Class Mentor Signature</p>
          </div>
          <div>
            <div className="h-12 border-b border-slate-700 mx-auto w-36"></div>
            <p className="mt-2 font-medium text-slate-300">Head of Department</p>
          </div>
          <div className="col-span-2 md:col-span-1">
            <div className="h-12 border-b border-slate-700 mx-auto w-36"></div>
            <p className="mt-2 font-medium text-slate-300">Dean of Academic Affairs</p>
          </div>
        </div>

      </div>
    </div>
  );
}
